# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2VlZjVjZWIwNjc5NThmMWE1MWRjNjYxZjZjMzQyMGMwNjZhNzFlNTVlOWY2ODZiMzdlYzRmYjIxMTVlZjA5YzI1YmNiNmZjOWNkZWJjYjRjM2MwMDRjYzBlZmVlMTdiNGViMmEwMDk0ZDEwYTQ1NTMxNmJlMDI2NDc4N2Y0Y2E=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: food4us
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: food4us
    password:
