package com.eco.food4us.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllergyIntoleranceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyIntoleranceAllPropertiesEquals(AllergyIntolerance expected, AllergyIntolerance actual) {
        assertAllergyIntoleranceAutoGeneratedPropertiesEquals(expected, actual);
        assertAllergyIntoleranceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyIntoleranceAllUpdatablePropertiesEquals(AllergyIntolerance expected, AllergyIntolerance actual) {
        assertAllergyIntoleranceUpdatableFieldsEquals(expected, actual);
        assertAllergyIntoleranceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyIntoleranceAutoGeneratedPropertiesEquals(AllergyIntolerance expected, AllergyIntolerance actual) {
        assertThat(actual)
            .as("Verify AllergyIntolerance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyIntoleranceUpdatableFieldsEquals(AllergyIntolerance expected, AllergyIntolerance actual) {
        assertThat(actual)
            .as("Verify AllergyIntolerance relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyIntoleranceUpdatableRelationshipsEquals(AllergyIntolerance expected, AllergyIntolerance actual) {
        assertThat(actual)
            .as("Verify AllergyIntolerance relationships")
            .satisfies(a -> assertThat(a.getUserProfiles()).as("check userProfiles").isEqualTo(expected.getUserProfiles()));
    }
}
