package com.eco.food4us.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DietaryEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDietaryEntryAllPropertiesEquals(DietaryEntry expected, DietaryEntry actual) {
        assertDietaryEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertDietaryEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDietaryEntryAllUpdatablePropertiesEquals(DietaryEntry expected, DietaryEntry actual) {
        assertDietaryEntryUpdatableFieldsEquals(expected, actual);
        assertDietaryEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDietaryEntryAutoGeneratedPropertiesEquals(DietaryEntry expected, DietaryEntry actual) {
        assertThat(actual)
            .as("Verify DietaryEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDietaryEntryUpdatableFieldsEquals(DietaryEntry expected, DietaryEntry actual) {
        assertThat(actual)
            .as("Verify DietaryEntry relevant properties")
            .satisfies(a -> assertThat(a.getConsumptionDate()).as("check consumptionDate").isEqualTo(expected.getConsumptionDate()))
            .satisfies(a -> assertThat(a.getConsumptionTime()).as("check consumptionTime").isEqualTo(expected.getConsumptionTime()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDietaryEntryUpdatableRelationshipsEquals(DietaryEntry expected, DietaryEntry actual) {
        assertThat(actual)
            .as("Verify DietaryEntry relationships")
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
