package com.eco.food4us.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IngredientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngredientAllPropertiesEquals(Ingredient expected, Ingredient actual) {
        assertIngredientAutoGeneratedPropertiesEquals(expected, actual);
        assertIngredientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngredientAllUpdatablePropertiesEquals(Ingredient expected, Ingredient actual) {
        assertIngredientUpdatableFieldsEquals(expected, actual);
        assertIngredientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngredientAutoGeneratedPropertiesEquals(Ingredient expected, Ingredient actual) {
        assertThat(actual)
            .as("Verify Ingredient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngredientUpdatableFieldsEquals(Ingredient expected, Ingredient actual) {
        assertThat(actual)
            .as("Verify Ingredient relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngredientUpdatableRelationshipsEquals(Ingredient expected, Ingredient actual) {
        assertThat(actual)
            .as("Verify Ingredient relationships")
            .satisfies(a -> assertThat(a.getRecipe()).as("check recipe").isEqualTo(expected.getRecipe()));
    }
}
